Add a footer
fetchYourBrain/react_phone-catalog pull request #23
Opened 2024-09-15 15:03 UTC by igor-romasiuk

2024-09-15 15:27 UTC, coldshein commented on src/components/Footer/Footer.module.scss
> +    padding: 32px 152px;
we don't need the inline paddings, just add <Container/> in footer

2024-09-15 15:28 UTC, coldshein commented on src/components/Footer/Footer.module.scss
> +  .backToTopBtn {
make the snake case

2024-09-15 15:34 UTC, coldshein requested changes
Great, fix some moments that I've written in the comments

2024-09-15 15:34 UTC, coldshein commented on src/components/Footer/Footer.tsx
> +                    <button className={styles.backToTopBtn} onClick={handleBackToTop}>↑</button>
also snake case

2024-09-16 06:50 UTC, igor-romasiuk commented
Hi! I have made the snake case but I have problem with inline paddings in footer

2024-09-17 16:59 UTC, closed without merging